spring.application.name=revakh
jwt.secret = ertyuilmnfdrtyui9876542qasxcvbnju890oijhgrwsxcvghy654w
jwt.expiration =3600000
server.port=8080


# ========== DATABASE CONFIGURATION ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/revakh_auth_service_db
spring.datasource.username=revakh_user
spring.datasource.password=jeethan7628
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA / HIBERNATE CONFIGURATION ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tauroshanjeeth@gmail.com
spring.mail.password=qpsm qizf mtji tbxq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Rabbit mq config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myapp
spring.rabbitmq.password=mypassword
spring.rabbitmq.virtual-host=myapp_vhost




