spring.application.name=api-gateway
server.port=8083
jwt.secret = ertyuilmnfdrtyui9876542qasxcvbnju890oijhgrwsxcvghy654w

spring.cloud.config.enabled=false

#routes for the services

#routes to auth service
spring.cloud.gateway.routes[0].id=auth_service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

#routes to finance service
spring.cloud.gateway.routes[1].id=finance_service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/finance/**

#routes to AI service
spring.cloud.gateway.routes[2].id=AI-service
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/AI/**


# Allow the Gateway to handle the PATCH method globally
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PATCH,DELETE,PUT,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

logging.level.root=info
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE


spring.autoconfigure.exclude=org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration