spring.application.name=revakh
server.port=8080

# ========== DATABASE CONFIGURATION ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/revakh_finance_service_db
spring.datasource.username=revakh_user
spring.datasource.password=jeethan7628
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA / HIBERNATE CONFIGURATION ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true



spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myapp
spring.rabbitmq.password=mypassword
spring.rabbitmq.virtual-host=myapp_vhost